### ISSUE TITLE
[docs] Duplicate notice field description heading in missing_feed_info_date

### ISSUE THREAD

**Issue by emmambd** [MobilityData/gtfs-validator#1353]
### Describe the problem

In the [missing_feed_info_date details accordion](https://github.com/MobilityData/gtfs-validator/blob/master/RULES.md#missing_feed_info_date), there's a duplicate Notice field description heading that should be removed. 

### Suggest a fix or an alternative

Remove it.

**Comment by isabelle-dr** [comment]
Hi @emmambd, thank you for opening this. 
I don't see a Notice field description heading, am I missing something?
<img width="997" alt="Screenshot 2023-05-31 at 2 20 14 AM" src="https://github.com/MobilityData/gtfs-validator/assets/63653518/9bd270a6-8d69-43f6-8ddd-44a61186aa32">

**Comment by emmambd** [comment]
<img width="1024" alt="Screenshot 2023-05-31 at 1 34 04 PM" src="https://github.com/MobilityData/gtfs-validator/assets/90632321/03eddf18-a5fa-409f-8148-bf65c3d5217c">

@isabelle-dr Here's what I'm referring to.

**Comment by cka-y** [comment]
I believe this has been fixed. @emmambd could you please confirm?

**Comment by emmambd** [comment]
@cka-y It's not: I can still see the same issue in https://gtfs-validator.mobilitydata.org/rules.html#missing_feed_info_date

**Comment by cka-y** [comment]
@emmambd it is indeed fixed by [Brian's changes](https://github.com/MobilityData/gtfs-validator/pull/1508) to the generation of the rule page from markdown to json. Here is what it looks like now:
 
![Screenshot 2023-07-04 at 3 56 10 PM](https://github.com/MobilityData/gtfs-validator/assets/60586858/e8f8f453-c665-41d2-a9af-282a96420238)

We didn't have a release after the previously mentioned changes were introduced - which is why we don't see the updates on the deployed rule page. Lmk if you think it would be ok to close this issue.

**Comment by emmambd** [comment]
@cka-y Got it - thanks for clarifying! I had a sinking feeling this was related to our release process right after I posted the comment 🙈

Should I check out the UI locally in the future to make sure I'm looking at the most recent changes?

**Comment by emmambd** [comment]
Marking as completed.

**Comment by cka-y** [comment]
I think we (the devs) can check it once we open the issue :)
